### ISSUE TITLE
How to get Updates

### ISSUE THREAD

**Issue by wasimjee** [TelegramBotsAPI/Telegram.Bots#1]
Can u please provide details on getting updates

**Comment by AmanAgnihotri** [comment]
Hi! Apologies for the late reply. The pandemic situation made my life such that I did not notice this issue until now.

To get updates, you need only [configure the BotClient](https://github.com/TelegramBotsAPI/Telegram.Bots#configure-the-bot-client) and then make the [GetUpdates](https://github.com/TelegramBotsAPI/Telegram.Bots/blob/master/src/Telegram.Bots/Requests/GetUpdates.cs) request with relevant parameters.

I have created a separate project, [Telegram.Bots.Extensions.Polling](https://github.com/TelegramBotsAPI/Telegram.Bots.Extensions.Polling), which polls for the updates as a background service and sends each update to a user-defined handler to manage it. It basically works as follows:

```c#
var offset = 0;

while (!token.IsCancellationRequested)
{
  var bot = GetBotClient();

  var response = await bot.HandleAsync(new GetUpdates
    {
      Offset = offset,
      Limit = _config.Limit,
      Timeout = _config.Timeout,
      AllowedUpdates = _config.AllowedUpdates
    }, token)
    .ConfigureAwait(false);

  if (!response.Ok || response.Result.Count <= 0) continue;

  foreach (var update in response.Result)
    await _handler.HandleAsync(bot, update, token);

  offset = response.Result[^1].Id + 1;
}
```

You can either try using its approach to poll for your own purposes or can use the project (it comes as a NuGet package too) to then simply define your update handler and work with it. That project has its own [README](https://github.com/TelegramBotsAPI/Telegram.Bots.Extensions.Polling) that you can check for more info on how to setup your update handler. The static typing will make defining the various cases for the update handler much easier and you can always ask more questions for clarification.
