### ISSUE TITLE
Settings for ASP.NET Core MVC

### ISSUE THREAD

**Issue by fox-15** [TelegramBotsAPI/Telegram.Bots#12]
Hello
Please help me configure for ASP.NET Core MVC
Unfortunately, the available information is common

**Comment by AmanAgnihotri** [comment]
Hi. You can add this NuGet package as a dependency: [Telegram.Bots.Extensions.AspNetCore](https://www.nuget.org/packages/Telegram.Bots.Extensions.AspNetCore).

Then you can check this part of the README to [Configure the Serializer with ASP.NET Core](https://github.com/TelegramBotsAPI/Telegram.Bots#configuring-the-serializer-with-aspnet-core).

Once that is done, you can setup the relevant webhook by making a [SetWebhook](https://github.com/TelegramBotsAPI/Telegram.Bots/blob/master/src/Telegram.Bots/Requests/Webhooks/SetWebhook.cs) request. Specify the Url there such that your backend can be reached by Telegram on that url.

Create a Controller which takes an [Update](https://github.com/TelegramBotsAPI/Telegram.Bots/blob/master/src/Telegram.Bots/Types/Update.cs) object as request body and process it accordingly by making other calls via the library or by returning a particular type of result as described in the [Telegram Bot API documentation](https://core.telegram.org/bots/faq#how-can-i-make-requests-in-response-to-updates).

I hope that helps.

If you still have issue, you can reply with some code that you have written so far where you are experiencing the issue and I'll try helping further!
